name: CI Lab (GitHub Actions)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"

  build-artifact:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p output
          echo "Hello from build job" > output/hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: output/

  test-artifact:
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-output
          path: output
      - run: cat output/hello.txt

  install-and-build-react:
    needs: test-artifact
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a placeholder for React build"
